# Generated by Django 4.0.3 on 2022-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_climbsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbsession',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
