# Generated by Django 4.0.3 on 2022-03-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_climbsession_created_at_alter_climbsession_all_blue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='climbsession',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.location'),
        ),
    ]
