# Generated by Django 4.0.3 on 2022-03-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.user')),
                ('number_of_session', models.IntegerField(default=0, verbose_name='Nombre de séance')),
                ('number_of_blues', models.IntegerField(default=0, verbose_name='Nombre total de bleue')),
                ('number_of_red', models.IntegerField(default=0, verbose_name='Nombre total de rouge')),
                ('time_spent_climbing', models.IntegerField(default=0, verbose_name='Temps passé à grimper (en min)')),
            ],
        ),
    ]
