# Generated by Django 4.0.3 on 2022-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_location_blueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to='location/'),
        ),
    ]
