# Generated by Django 4.0.3 on 2022-03-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_routetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='number_of_sector',
            field=models.IntegerField(default=0),
        ),
    ]
