# Generated by Django 4.0.3 on 2022-03-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_location_number_of_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.location')),
                ('tags', models.ManyToManyField(related_name='routes', to='stats.routetag')),
            ],
        ),
    ]
