# Generated by Django 4.0.3 on 2022-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_climbsession_routes_alter_climbroute_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbroute',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='routes', to='stats.routetag'),
        ),
        migrations.AlterField(
            model_name='climbsession',
            name='routes',
            field=models.ManyToManyField(blank=True, to='stats.climbroute'),
        ),
    ]
