# Generated by Django 4.0.3 on 2022-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_alter_climbroute_tags_alter_climbsession_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbroute',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], default='Blue', max_length=4),
        ),
    ]
