# Generated by Django 4.0.3 on 2022-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_climbroute_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbsession',
            name='routes',
        ),
        migrations.AddField(
            model_name='climbroute',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='route/'),
        ),
        migrations.AlterField(
            model_name='climbroute',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], default='Blue', max_length=4),
        ),
    ]
