# Generated by Django 4.0.3 on 2022-03-13 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_remove_climbsession_routes_climbroute_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbRouteTry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True, verbose_name='Réussie?')),
                ('is_flashed', models.BooleanField(default=False, verbose_name='Flashée?')),
                ('climb_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_tried', to='stats.climbroute')),
                ('climb_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.climbsession')),
            ],
        ),
    ]
