# Generated by Django 4.0.3 on 2022-03-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_climbroutetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbroutetry',
            name='climb_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.climbroute'),
        ),
        migrations.AlterField(
            model_name='climbroutetry',
            name='climb_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_tried', to='stats.climbsession'),
        ),
    ]
