# Generated by Django 4.0.3 on 2022-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_alter_climbroutetry_climb_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbroute',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], default='BLUE', max_length=4),
        ),
    ]
