# Generated by Django 4.0.3 on 2022-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_alter_climbroutetry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbsession',
            name='ratio_blue_session',
            field=models.FloatField(default=0, verbose_name='Ratio de bleues grimpée dans la séance'),
        ),
        migrations.AddField(
            model_name='climbsession',
            name='ratio_red_session',
            field=models.FloatField(default=0, verbose_name='Ratio de rouges grimpée dans la séance'),
        ),
    ]
