# Generated by Django 4.0.3 on 2022-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_climbsession_ratio_blue_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbsession',
            name='ratio_blue_session',
            field=models.IntegerField(default=0, verbose_name='Ratio de bleues grimpée dans la séance'),
        ),
        migrations.AlterField(
            model_name='climbsession',
            name='ratio_red_session',
            field=models.IntegerField(default=0, verbose_name='Ratio de rouges grimpée dans la séance'),
        ),
    ]
