# Generated by Django 4.0.3 on 2022-04-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_alter_climbsession_ratio_blue_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbSessionStatColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], default='BLUE', max_length=4)),
                ('new_routes', models.IntegerField(default=0, verbose_name='Nombre de nouvelles pistes réussies')),
                ('all_routes', models.IntegerField(default=0, verbose_name='Toutes les pistes réussies')),
                ('ratio_route_session', models.IntegerField(default=0, verbose_name='Ratio de pistes grimpée dans la séance')),
                ('climb_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.climbsession')),
            ],
        ),
    ]
