# Generated by Django 4.0.3 on 2022-04-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_climbsessionstatcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbsession',
            name='all_blue',
        ),
        migrations.RemoveField(
            model_name='climbsession',
            name='all_red',
        ),
        migrations.RemoveField(
            model_name='climbsession',
            name='new_blue',
        ),
        migrations.RemoveField(
            model_name='climbsession',
            name='new_red',
        ),
        migrations.RemoveField(
            model_name='climbsession',
            name='ratio_blue_session',
        ),
        migrations.RemoveField(
            model_name='climbsession',
            name='ratio_red_session',
        ),
    ]
