# Generated by Django 4.0.3 on 2022-04-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_remove_climbsession_all_blue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbsessionstatcolor',
            name='ratio_route_location',
            field=models.IntegerField(default=0, verbose_name='Ratio de pistes validées dans la salle'),
        ),
    ]
