# Generated by Django 4.0.3 on 2022-04-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0029_climbsessionstatcolor_ratio_route_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbsessionstatcolor',
            name='climb_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.climbsession'),
        ),
    ]
