# Generated by Django 4.0.3 on 2022-04-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_alter_climbsessionstatcolor_climb_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='climb_profile', serialize=False, to='stats.user'),
        ),
    ]
