# Generated by Django 4.0.3 on 2022-04-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_alter_climbuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbUserStatColor',
            fields=[
                ('climb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='color_stats', serialize=False, to='stats.climbuser')),
                ('color', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], default='BLUE', max_length=4)),
                ('number_of_routes_succeeded', models.IntegerField(default=0, verbose_name='Nombre total de pistes réussies')),
                ('number_of_routes_flashed', models.IntegerField(default=0, verbose_name='Nombre total de pistes flashées')),
                ('number_of_routes_tried', models.IntegerField(default=0, verbose_name='Nombre total de pistes ratées')),
            ],
        ),
    ]
