# Generated by Django 4.0.3 on 2022-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_remove_climbuser_number_of_blues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climbsessionstatcolor',
            old_name='all_routes',
            new_name='all_routes_succeeded',
        ),
        migrations.RenameField(
            model_name='climbsessionstatcolor',
            old_name='new_routes',
            new_name='new_routes_succeeded',
        ),
    ]
