# Generated by Django 4.0.3 on 2022-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0035_rename_all_routes_climbsessionstatcolor_all_routes_succeeded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbsessionstatcolor',
            name='routes_flashed',
            field=models.IntegerField(default=0, verbose_name='Nombre de pistes flashées'),
        ),
        migrations.AddField(
            model_name='climbsessionstatcolor',
            name='routes_tried',
            field=models.IntegerField(default=0, verbose_name='Nombre de pistes essayées'),
        ),
    ]
